name: Copy folder to other branch
on:
  workflow_dispatch:
  push:
    branches:
      - build
    paths:
      - "**.pdf"
jobs:
  copy:
    name: Copy pdf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy
        run: |
          git status
          git fetch
          git restore --source build origin/build/syllabus.pdf
          
