name: Copy folder to other branch
on:
  workflow_dispatch:
  push:
    branches:
      - build
    paths:
      - "**.pdf"
jobs:
  copy:
    name: Copy pdf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SOURCE_BRANCH: ''
          TARGET_BRANCH: 'web'
        run: |
          git checkout web -- "syllabus.pdf" # copy files from the source branch
